/* The following code was generated by JFlex 1.7.0 */

class Symbol{
    public int id;
    public String string;

    Symbol(String string, int id){
        this.id = id;
        this.string = string;
    }
}


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>/Users/parsahejabi/University/Term 6/CompilerDesign/Homeworks/Scanner/src/main/java/CSpecifications.flex</tt>
 */
class CScanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;
  public static final int CHAR = 4;
  public static final int ENDCHAR = 6;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3, 3
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\10\0\1\0\1\14\1\16\2\0\1\15\22\0\1\14\1\0\1\46"+
    "\4\0\1\47\2\0\1\20\1\13\1\0\1\13\1\10\1\17\1\3"+
    "\11\2\7\0\4\7\1\12\1\7\21\1\1\5\2\1\1\0\1\50"+
    "\2\0\1\1\1\0\1\21\1\33\1\27\1\37\1\11\1\6\1\36"+
    "\1\31\1\25\1\1\1\34\1\35\1\43\1\26\1\24\1\45\1\1"+
    "\1\32\1\30\1\23\1\22\1\42\1\41\1\4\1\44\1\40\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uff95\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\4\0\1\1\1\2\2\3\1\2\1\1\1\2\1\4"+
    "\2\5\1\1\15\2\1\6\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\3\0\5\2\1\17\1\0"+
    "\3\2\1\20\13\2\1\20\2\2\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\0\1\3\4\2"+
    "\2\17\2\0\25\2\1\0\26\2";

  private static int [] zzUnpackAction() {
    int [] result = new int[127];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\51\0\122\0\173\0\244\0\315\0\366\0\u011f"+
    "\0\u0148\0\u0171\0\u019a\0\244\0\u01c3\0\244\0\u01ec\0\u0215"+
    "\0\u023e\0\u0267\0\u0290\0\u02b9\0\u02e2\0\u030b\0\u0334\0\u035d"+
    "\0\u0386\0\u03af\0\u03d8\0\u0401\0\244\0\244\0\u042a\0\244"+
    "\0\u0453\0\244\0\u047c\0\244\0\u0171\0\u04a5\0\u04ce\0\u04f7"+
    "\0\u0520\0\u0549\0\u0572\0\u059b\0\u05c4\0\u05ed\0\u0616\0\u063f"+
    "\0\u0668\0\u0691\0\315\0\u06ba\0\u06e3\0\u070c\0\u0735\0\u075e"+
    "\0\u0787\0\u07b0\0\u07d9\0\u0802\0\u082b\0\u0854\0\u087d\0\u08a6"+
    "\0\u08cf\0\244\0\244\0\244\0\244\0\244\0\244\0\244"+
    "\0\244\0\u0171\0\u04f7\0\u08f8\0\u0921\0\u094a\0\u0973\0\u099c"+
    "\0\244\0\u09c5\0\u09ee\0\u0a17\0\u0a40\0\u0a69\0\u0a92\0\u0abb"+
    "\0\u0ae4\0\u0b0d\0\u0b36\0\u0b5f\0\u0b88\0\u0bb1\0\u0bda\0\u0c03"+
    "\0\u0c2c\0\u0c55\0\u0c7e\0\u0ca7\0\u0cd0\0\u0cf9\0\u0d22\0\u0d4b"+
    "\0\u0d74\0\u0d9d\0\u0dc6\0\u0def\0\u0e18\0\u0e41\0\u0e6a\0\u0e93"+
    "\0\u0ebc\0\u0ee5\0\u0f0e\0\u0f37\0\u0f60\0\u0f89\0\u0fb2\0\u0fdb"+
    "\0\u1004\0\u102d\0\u1056\0\u107f\0\u10a8\0\u10d1\0\u10fa";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[127];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\5\1\6\1\7\1\10\2\6\1\11\1\6\1\12"+
    "\1\13\1\6\1\5\1\14\1\15\1\16\1\17\1\5"+
    "\1\20\1\21\1\22\1\6\1\23\1\6\1\24\1\25"+
    "\1\6\1\26\1\27\1\6\1\30\1\31\1\32\1\6"+
    "\1\33\1\34\3\6\1\35\1\36\1\5\15\37\2\5"+
    "\27\37\1\40\1\37\1\41\15\42\2\5\30\42\1\5"+
    "\1\43\47\5\1\44\1\5\52\0\7\6\1\0\2\6"+
    "\6\0\25\6\5\0\2\7\4\0\1\45\2\46\40\0"+
    "\2\47\2\50\2\0\1\45\2\46\37\0\7\6\1\0"+
    "\2\6\6\0\3\6\1\51\10\6\1\52\10\6\5\0"+
    "\2\45\46\0\3\6\1\53\3\6\1\0\2\6\6\0"+
    "\5\6\1\54\6\6\1\55\10\6\21\0\1\16\51\0"+
    "\1\56\1\57\31\0\7\6\1\0\2\6\6\0\1\6"+
    "\1\60\23\6\4\0\7\6\1\0\2\6\6\0\5\6"+
    "\1\61\17\6\4\0\7\6\1\0\2\6\6\0\23\6"+
    "\1\62\1\6\4\0\5\6\1\63\1\6\1\0\2\6"+
    "\6\0\5\6\1\64\17\6\4\0\7\6\1\0\2\6"+
    "\6\0\1\55\2\6\1\65\4\6\1\66\14\6\4\0"+
    "\7\6\1\0\2\6\6\0\2\6\1\67\1\6\1\70"+
    "\3\6\1\71\7\6\1\72\4\6\4\0\7\6\1\0"+
    "\1\73\1\6\6\0\25\6\4\0\7\6\1\0\2\6"+
    "\6\0\11\6\1\74\13\6\4\0\7\6\1\0\2\6"+
    "\6\0\3\6\1\75\21\6\4\0\7\6\1\0\2\6"+
    "\6\0\3\6\1\60\21\6\4\0\7\6\1\0\1\76"+
    "\1\6\6\0\3\6\1\77\21\6\4\0\7\6\1\0"+
    "\2\6\6\0\10\6\1\100\14\6\4\0\7\6\1\0"+
    "\2\6\6\0\3\6\1\101\21\6\3\0\15\37\2\0"+
    "\27\37\1\0\1\37\24\0\1\102\2\0\1\103\3\0"+
    "\1\104\13\0\1\105\25\0\1\106\2\0\1\107\3\0"+
    "\1\110\13\0\1\111\4\0\2\45\7\0\1\112\37\0"+
    "\2\47\4\0\1\45\2\46\40\0\2\113\2\0\2\113"+
    "\1\0\2\113\6\0\1\113\5\0\1\113\3\0\1\113"+
    "\3\0\1\113\12\0\7\6\1\0\2\6\6\0\11\6"+
    "\1\63\13\6\4\0\7\6\1\0\2\6\6\0\3\6"+
    "\1\114\21\6\4\0\7\6\1\0\2\6\6\0\2\6"+
    "\1\115\22\6\4\0\7\6\1\0\2\6\6\0\1\6"+
    "\1\116\23\6\4\0\7\6\1\0\2\6\6\0\7\6"+
    "\1\117\15\6\3\0\15\56\1\120\1\121\32\56\20\122"+
    "\1\123\30\122\1\0\7\6\1\0\2\6\6\0\2\6"+
    "\1\124\22\6\4\0\7\6\1\0\2\6\6\0\4\6"+
    "\1\125\2\6\1\126\15\6\4\0\7\6\1\0\2\6"+
    "\6\0\24\6\1\127\4\0\7\6\1\0\2\6\6\0"+
    "\2\6\1\63\22\6\4\0\7\6\1\0\2\6\6\0"+
    "\5\6\1\130\17\6\4\0\7\6\1\0\2\6\6\0"+
    "\1\51\24\6\4\0\7\6\1\0\2\6\6\0\1\131"+
    "\10\6\1\132\13\6\4\0\7\6\1\0\2\6\6\0"+
    "\15\6\1\133\1\6\1\134\5\6\4\0\7\6\1\0"+
    "\2\6\6\0\3\6\1\135\21\6\4\0\7\6\1\0"+
    "\2\6\6\0\4\6\1\136\20\6\4\0\7\6\1\0"+
    "\2\6\6\0\2\6\1\137\12\6\1\140\7\6\4\0"+
    "\7\6\1\0\1\141\1\6\6\0\25\6\4\0\7\6"+
    "\1\0\2\6\6\0\5\6\1\142\17\6\4\0\5\6"+
    "\1\143\1\6\1\0\2\6\6\0\25\6\4\0\7\6"+
    "\1\0\2\6\6\0\1\6\1\144\23\6\4\0\7\6"+
    "\1\0\2\6\6\0\4\6\1\145\20\6\4\0\7\6"+
    "\1\0\2\6\6\0\4\6\1\146\7\6\1\147\10\6"+
    "\4\0\7\6\1\0\2\6\6\0\1\64\24\6\4\0"+
    "\7\6\1\0\1\150\1\6\6\0\25\6\4\0\7\6"+
    "\1\0\2\6\6\0\22\6\1\63\2\6\4\0\7\6"+
    "\1\0\1\63\1\6\6\0\25\6\21\0\1\121\32\0"+
    "\20\122\1\151\30\122\17\0\1\121\1\123\31\0\7\6"+
    "\1\0\2\6\6\0\3\6\1\63\21\6\4\0\7\6"+
    "\1\0\2\6\6\0\3\6\1\152\21\6\4\0\7\6"+
    "\1\0\2\6\6\0\4\6\1\153\20\6\4\0\7\6"+
    "\1\0\1\154\1\6\6\0\25\6\4\0\7\6\1\0"+
    "\2\6\6\0\2\6\1\155\4\6\1\64\15\6\4\0"+
    "\7\6\1\0\2\6\6\0\2\6\1\156\22\6\4\0"+
    "\7\6\1\0\2\6\6\0\1\6\1\157\23\6\4\0"+
    "\7\6\1\0\2\6\6\0\5\6\1\160\17\6\4\0"+
    "\7\6\1\0\1\161\1\6\6\0\25\6\4\0\7\6"+
    "\1\0\2\6\6\0\11\6\1\64\13\6\4\0\7\6"+
    "\1\0\2\6\6\0\2\6\1\162\22\6\4\0\7\6"+
    "\1\0\2\6\6\0\1\6\1\150\23\6\4\0\7\6"+
    "\1\0\2\6\6\0\4\6\1\163\20\6\4\0\7\6"+
    "\1\0\2\6\6\0\1\164\24\6\4\0\7\6\1\0"+
    "\2\6\6\0\15\6\1\63\7\6\4\0\7\6\1\0"+
    "\2\6\6\0\1\165\24\6\4\0\7\6\1\0\2\6"+
    "\6\0\12\6\1\145\12\6\4\0\7\6\1\0\2\6"+
    "\6\0\14\6\1\117\10\6\4\0\7\6\1\0\2\6"+
    "\6\0\16\6\1\63\6\6\4\0\7\6\1\0\2\6"+
    "\6\0\1\166\24\6\4\0\7\6\1\0\2\6\6\0"+
    "\11\6\1\152\13\6\3\0\17\122\1\121\1\151\30\122"+
    "\1\0\7\6\1\0\2\6\6\0\5\6\1\63\17\6"+
    "\4\0\7\6\1\0\2\6\6\0\15\6\1\133\7\6"+
    "\4\0\7\6\1\0\2\6\6\0\16\6\1\167\6\6"+
    "\4\0\7\6\1\0\2\6\6\0\4\6\1\170\20\6"+
    "\4\0\7\6\1\0\2\6\6\0\4\6\1\171\20\6"+
    "\4\0\7\6\1\0\2\6\6\0\6\6\1\64\16\6"+
    "\4\0\7\6\1\0\1\146\1\6\6\0\25\6\4\0"+
    "\7\6\1\0\2\6\6\0\3\6\1\172\21\6\4\0"+
    "\7\6\1\0\2\6\6\0\6\6\1\173\16\6\4\0"+
    "\7\6\1\0\2\6\6\0\7\6\1\174\15\6\4\0"+
    "\7\6\1\0\2\6\6\0\13\6\1\63\11\6\4\0"+
    "\7\6\1\0\2\6\6\0\1\6\1\175\23\6\4\0"+
    "\7\6\1\0\2\6\6\0\2\6\1\100\22\6\4\0"+
    "\7\6\1\0\1\172\1\6\6\0\25\6\4\0\7\6"+
    "\1\0\2\6\6\0\5\6\1\176\17\6\4\0\7\6"+
    "\1\0\2\6\6\0\6\6\1\63\16\6\4\0\5\6"+
    "\1\63\1\6\1\0\2\6\6\0\25\6\4\0\7\6"+
    "\1\0\2\6\6\0\10\6\1\63\14\6\4\0\7\6"+
    "\1\0\2\6\6\0\2\6\1\177\22\6\4\0\7\6"+
    "\1\0\2\6\6\0\14\6\1\64\10\6\4\0\7\6"+
    "\1\0\2\6\6\0\1\6\1\117\23\6\4\0\7\6"+
    "\1\0\1\51\1\6\6\0\25\6\3\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4387];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\4\0\1\11\6\1\1\11\1\1\1\11\16\1\2\11"+
    "\1\1\1\11\1\1\1\11\1\1\1\11\1\1\3\0"+
    "\6\1\1\0\22\1\10\11\1\0\6\1\1\11\2\0"+
    "\25\1\1\0\26\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[127];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    StringBuffer string = new StringBuffer();


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  CScanner(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 152) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Symbol CScannerFunction() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { throw new Error("Illegal character <"+yytext()+">");
            } 
            // fall through
          case 25: break;
          case 2: 
            { return new Symbol(yytext(), 2);
            } 
            // fall through
          case 26: break;
          case 3: 
            { return new Symbol(yytext(), 3);
            } 
            // fall through
          case 27: break;
          case 4: 
            { return new Symbol(yytext(), 8);
            } 
            // fall through
          case 28: break;
          case 5: 
            { return new Symbol(yytext(), 9);
            } 
            // fall through
          case 29: break;
          case 6: 
            { string.setLength(0); yybegin(STRING);
            } 
            // fall through
          case 30: break;
          case 7: 
            { string.setLength(0); yybegin(CHAR);
            } 
            // fall through
          case 31: break;
          case 8: 
            { string.append(yytext());
            } 
            // fall through
          case 32: break;
          case 9: 
            { yybegin(YYINITIAL); return new Symbol(string.toString(), 5);
            } 
            // fall through
          case 33: break;
          case 10: 
            { string.append('\\');
            } 
            // fall through
          case 34: break;
          case 11: 
            { string.append(yytext()); yybegin(ENDCHAR);
            } 
            // fall through
          case 35: break;
          case 12: 
            { string.append('\\'); yybegin(ENDCHAR);
            } 
            // fall through
          case 36: break;
          case 13: 
            { yybegin(YYINITIAL); return new Symbol(string.toString(), 6);
            } 
            // fall through
          case 37: break;
          case 14: 
            { return new Symbol(yytext(), 4);
            } 
            // fall through
          case 38: break;
          case 15: 
            { return new Symbol(yytext(), 7);
            } 
            // fall through
          case 39: break;
          case 16: 
            { return new Symbol(yytext(), 1);
            } 
            // fall through
          case 40: break;
          case 17: 
            { string.append('\t');
            } 
            // fall through
          case 41: break;
          case 18: 
            { string.append('\n');
            } 
            // fall through
          case 42: break;
          case 19: 
            { string.append('\r');
            } 
            // fall through
          case 43: break;
          case 20: 
            { string.append('\"');
            } 
            // fall through
          case 44: break;
          case 21: 
            { string.append('\t'); yybegin(ENDCHAR);
            } 
            // fall through
          case 45: break;
          case 22: 
            { string.append('\n'); yybegin(ENDCHAR);
            } 
            // fall through
          case 46: break;
          case 23: 
            { string.append('\r'); yybegin(ENDCHAR);
            } 
            // fall through
          case 47: break;
          case 24: 
            { string.append('\"'); yybegin(ENDCHAR);
            } 
            // fall through
          case 48: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
