
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int IDENTIFIER = 24;
  public static final int TIMES = 18;
  public static final int BOOL = 65;
  public static final int LESS_THAN = 12;
  public static final int GREATER_THAN_EQUAL_TO = 10;
  public static final int PREFIX_PLUS_PLUS = 28;
  public static final int GREATER_THAN = 13;
  public static final int CONST = 62;
  public static final int AND_BITWISE = 21;
  public static final int OR_COND = 15;
  public static final int PLUS_EQUAL = 55;
  public static final int NOT_EXPR = 36;
  public static final int BOOL_CONST = 5;
  public static final int UNTIL = 41;
  public static final int COMMA = 53;
  public static final int RPAREN = 33;
  public static final int XOR_BITWISE = 23;
  public static final int SIZE_OF = 37;
  public static final int DOUBLE = 69;
  public static final int STRING_CONST = 6;
  public static final int LPAREN = 32;
  public static final int TILDE = 35;
  public static final int FLOAT = 66;
  public static final int RECORD = 63;
  public static final int POSTFIX_MINUS_MINUS = 31;
  public static final int MOD = 20;
  public static final int REAL_CONST = 3;
  public static final int AND_COND = 14;
  public static final int OR_BITWISE = 22;
  public static final int LONG = 67;
  public static final int PLUS = 16;
  public static final int DIVIDE = 19;
  public static final int MINUS_UNARY = 34;
  public static final int EQUAL = 54;
  public static final int CHAR = 68;
  public static final int NOT_EQUAL_TO = 9;
  public static final int SWITCH = 46;
  public static final int DIVIDE_EQUAL = 58;
  public static final int FOR = 38;
  public static final int EXTERN = 73;
  public static final int VOID = 71;
  public static final int POSTFIX_PLUS_PLUS = 30;
  public static final int RETURN = 59;
  public static final int INT_CONST = 2;
  public static final int ELSE = 45;
  public static final int BREAK = 60;
  public static final int DOT = 27;
  public static final int INT = 64;
  public static final int TIMES_EQUAL = 57;
  public static final int EOF = 0;
  public static final int SEMICOLON = 39;
  public static final int DEFAULT = 51;
  public static final int FUNCTION = 74;
  public static final int REPEAT = 40;
  public static final int LESS_THAN_EQUAL_TO = 11;
  public static final int MINUS = 17;
  public static final int EQUAL_TO = 8;
  public static final int IN = 43;
  public static final int error = 1;
  public static final int CHAR_CONST = 4;
  public static final int CONTINUE = 61;
  public static final int IF = 44;
  public static final int MINUS_EQUAL = 56;
  public static final int OF = 47;
  public static final int END = 52;
  public static final int COLON = 48;
  public static final int FOREACH = 42;
  public static final int LONG_CONST = 7;
  public static final int RBRACKET = 26;
  public static final int PREFIX_MINUS_MINUS = 29;
  public static final int BEGIN = 49;
  public static final int CASE = 50;
  public static final int STRING = 70;
  public static final int LBRACKET = 25;
  public static final int AUTO = 72;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT_CONST",
  "REAL_CONST",
  "CHAR_CONST",
  "BOOL_CONST",
  "STRING_CONST",
  "LONG_CONST",
  "EQUAL_TO",
  "NOT_EQUAL_TO",
  "GREATER_THAN_EQUAL_TO",
  "LESS_THAN_EQUAL_TO",
  "LESS_THAN",
  "GREATER_THAN",
  "AND_COND",
  "OR_COND",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "MOD",
  "AND_BITWISE",
  "OR_BITWISE",
  "XOR_BITWISE",
  "IDENTIFIER",
  "LBRACKET",
  "RBRACKET",
  "DOT",
  "PREFIX_PLUS_PLUS",
  "PREFIX_MINUS_MINUS",
  "POSTFIX_PLUS_PLUS",
  "POSTFIX_MINUS_MINUS",
  "LPAREN",
  "RPAREN",
  "MINUS_UNARY",
  "TILDE",
  "NOT_EXPR",
  "SIZE_OF",
  "FOR",
  "SEMICOLON",
  "REPEAT",
  "UNTIL",
  "FOREACH",
  "IN",
  "IF",
  "ELSE",
  "SWITCH",
  "OF",
  "COLON",
  "BEGIN",
  "CASE",
  "DEFAULT",
  "END",
  "COMMA",
  "EQUAL",
  "PLUS_EQUAL",
  "MINUS_EQUAL",
  "TIMES_EQUAL",
  "DIVIDE_EQUAL",
  "RETURN",
  "BREAK",
  "CONTINUE",
  "CONST",
  "RECORD",
  "INT",
  "BOOL",
  "FLOAT",
  "LONG",
  "CHAR",
  "DOUBLE",
  "STRING",
  "VOID",
  "AUTO",
  "EXTERN",
  "FUNCTION"
  };
}

